// Page numbers relate to this document:
// https://uefi.org/sites/default/files/resources/UEFI_Spec_2_8_final.pdf

#include <uefi/types.h>

// EFI_FILE_SYSTEM_PROTOCOL_REVISION(Page 504)
#define EFI_FILE_SYSTEM_PROTOCOL_REVISION 0x00010000

// EFI_FILE_PROTOCOL(Page 507)
#define EFI_FILE_PROTOCOL_REVISION 0x00010000
#define EFI_FILE_PROTOCOL_REVISION2 0x00020000
#define EFI_FILE_PROTOCOL_LATEST_REVISION EFI_FILE_PROTOCOL_REVISION2

typedef struct _EFI_FILE_PROTOCOL {
  UINT64 Revision;
  EFI_FILE_OPEN Open;
  EFI_FILE_CLOSE Close;
  EFI_FILE_DELETE Delete;
  EFI_FILE_READ Read;
  EFI_FILE_WRITE Write;
  EFI_FILE_GET_POSITION GetPosition;
  EFI_FILE_SET_POSITION SetPosition;
  EFI_FILE_GET_INFO GetInfo;
  EFI_FILE_SET_INFO SetInfo;
  EFI_FILE_FLUSH Flush;
  EFI_FILE_OPEN_EX OpenEx; // Rev2
  EFI_FILE_READ_EX ReadEx; // Rev2
  EFI_FILE_WRITE_EX WriteEx; // Rev2
  EFI_FILE_FLUSH_EX FlushEx; // Rev2
} EFI_FILE_PROTOCOL;

// EFI_SIMPLE_TEXT_INPUT_PROTOCOL_OPEN_VOLUME(Page 505)
typedef EFI_STATUS (EFIAPI *EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME) (EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME *This, EFI_FILE_PROTOCOL **Root);

// EFI_SIMPLE_FILE_SYSTEM_PROTOCOL(Page 504)
typedef struct _EFI_SIMPLE_FILE_SYSTEM_PROTOCOL {
  UINT64 Revision;
  EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME OpenVolume;
} EFI_SIMPLE_FILE_SYSTEM_PROTOCOL;
