// Page numbers relate to this document:
// https://uefi.org/sites/default/files/resources/UEFI_Spec_2_8_final.pdf

#include <uefi/types.h>

#ifndef UEFI_SIMPLE_FILE_SYSTEM_PROTOCOL_H
#define UEFI_SIMPLE_FILE_SYSTEM_PROTOCOL_H

struct _EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL;

// EFI_FILE_SYSTEM_PROTOCOL_REVISION(Page 504)
#define EFI_FILE_SYSTEM_PROTOCOL_REVISION 0x00010000

// EFI_SIMPLE_TEXT_INPUT_PROTOCOL_OPEN_VOLUME(Page 505)
typedef EFI_STATUS (*EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME) (EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME *This, EFI_FILE_PROTOCOL **Root);

// EFI_SIMPLE_FILE_SYSTEM_PROTOCOL(Page 504)
typedef struct _EFI_SIMPLE_FILE_SYSTEM_PROTOCOL {
  UINT64 Revision;
  EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME OpenVolume;
} EFI_SIMPLE_FILE_SYSTEM_PROTOCOL;

#endif
