// Page numbers relate to this document:
// https://uefi.org/sites/default/files/resources/UEFI_Spec_2_8_final.pdf

#include <uefi/types.h>

#ifndef SIMPLE_TEXT_INPUT_EX_H
#define SIMPLE_TEXT_INPUT_EX_H

struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL;

// KeyShiftState's(Page 507)
#define EFI_SHIFT_STATE_VALID 0x80000000
#define EFI_RIGHT_SHIFT_PRESSED 0x00000001
#define EFI_LEFT_SHIFT_PRESSED 0x00000002
#define EFI_RIGHT_CONTROL_PRESSED 0x00000004
#define EFI_LEFT_CONTROL_PRESSED 0x00000008
#define EFI_RIGHT_ALT_PRESSED 0x00000010
#define EFI_LEFT_ALT_PRESSED 0x00000020
#define EFI_RIGHT_LOGO_PRESSED 0x00000040
#define EFI_LEFT_LOGO_PRESSED 0x00000080
#define EFI_MENU_KEY_PRESSED 0x00000100
#define EFI_SYS_REQ_PRESSED 0x00000200

// EFI_KEY_TOGGLE_STATE(Page 507)
typedef UINT8 EFI_KEY_TOGGLE_STATE;

#define EFI_TOGGLE_STATE_VALID 0x80
#define EFI_KEY_STATE_EXPOSED 0x40
#define EFI_SCROLL_LOCK_ACTIVE 0x01
#define EFI_NUM_LOCK_ACTIVE 0x02
#define EFI_CAPS_LOCK_ACTIVE 0x04

// EFI_INPUT_RESET_EX(Page 505)
typedef EFI_STATUS (*EFI_INPUT_RESET_EX) (struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *This, BOOLEAN ExtendedVerification);

// EFI_KEY_STATE(Page 506)
typedef struct EFI_KEY_STATE {
  UINT32 KeyShiftState;
  EFI_KEY_TOGGLE_STATE KeyToggleState;
} EFI_KEY_STATE;

// EFI_KEY_DATA(Page 506)
typedef struct {
  EFI_INPUT_KEY Key;
  EFI_KEY_STATE KeyState;
} EFI_KEY_DATA;

// EFI_INPUT_READ_KEY_EX(Page 506)
typedef EFI_STATUS (*EFI_INPUT_READ_KEY_EX) (struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *This, EFI_KEY_DATA *KeyData);

// EFI_SET_STATE(Page 508)
typedef EFI_STATUS (*EFI_SET_STATE) (struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *This, EFI_KEY_TOGGLE_STATE *KeyToggleState);

// EFI_KEY_NOTIFY_FUNCTION(Page 510)
typedef EFI_STATUS (*EFI_KEY_NOTIFY_FUNCTION) (EFI_KEY_DATA *KeyData);

// EFI_REGISTER_PROTOCOL_NOTIFY(Page 509)
typedef EFI_STATUS (*EFI_REGISTER_KEYSTROKE_NOTIFY) (struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *This, EFI_KEY_DATA *KeyData, EFI_KEY_NOTIFY_FUNCTION KeyNotificationFunction, VOID **NotifyHandle);

// EFI_UNREGISTER_KEYSTROKE_NOTIFY(Page 510)
typedef EFI_STATUS (*EFI_UNREGISTER_KEYSTROKE_NOTIFY) (struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *This, VOID *NotificationHandle);

// EFI_SIMPLE_TEXT_PROTOCOL(Page 504)
#define EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL_GUID {0xdd9e7534, 0x7762, 0x4698, {0x8c, 0x14, 0xf5, 0x85, 0x17, 0xa6, 0x25, 0xaa}}

typedef struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL {
  EFI_INPUT_RESET_EX Reset;
  EFI_INPUT_READ_KEY_EX ReadKeyStrokeEx;
  EFI_EVENT WaitForKeyEx;
  EFI_SET_STATE SetState;
  EFI_REGISTER_KEYSTROKE_NOTIFY RegisterKeyNotify;
  EFI_UNREGISTER_KEYSTROKE_NOTIFY UnregisterKeyNotify;
} EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL;

#endif
